# Generated by Django 5.1.3 on 2024-12-04 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moxiedevice',
            name='permit',
            field=models.IntegerField(choices=[(1, 'UNKNOWN'), (2, 'PENDING'), (3, 'ALLOWED')], default=1),
        ),
        migrations.AlterField(
            model_name='moxielogs',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.moxiedevice'),
        ),
    ]
