# Generated by Django 5.1.3 on 2024-12-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0005_hiveconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='moxiedevice',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
