# Generated by Django 5.1.3 on 2024-12-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0007_mentorbehavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='moxiedevice',
            name='last_connect',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moxiedevice',
            name='last_disconnect',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
