# Generated by Django 5.1.3 on 2024-12-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0008_moxiedevice_last_connect_moxiedevice_last_disconnect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moxiedevice',
            name='last_connect',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moxiedevice',
            name='last_disconnect',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
