# Generated by Django 5.1.3 on 2025-01-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0010_hiveconfiguration_common_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moxieschedule',
            name='source_version',
            field=models.IntegerField(default=1),
        ),
    ]
