# Generated by Django 5.1.3 on 2025-01-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0011_moxieschedule_source_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepromptchat',
            name='source_version',
            field=models.IntegerField(default=1),
        ),
    ]
