# Generated by Django 5.1.3 on 2025-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0013_globalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepromptchat',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
