# Generated by Django 5.1.3 on 2025-02-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0015_persistentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalresponse',
            name='source_version',
            field=models.IntegerField(default=1),
        ),
    ]
